apiVersion: v1
kind: Service
metadata:
  name: cm
  namespace: appveen
spec:
  type: ClusterIP
  selector:
    app: cm
  ports:
    - protocol: TCP
      name: http-port
      port: 80
      targetPort: 11011
    - protocol: TCP
      name: https-port
      port: 443
      targetPort: 11443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm
  namespace: appveen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm
  template:
    metadata:
      labels:
        app: cm
    spec:
      serviceAccountName: ds-admin
      containers:
        - name: cm
          image: 'appveen/data.stack.cm:2.7.0'
          ports:
            - containerPort: 11011
            - containerPort: 11443
          livenessProbe:
            httpGet:
              path: /cm/internal/health/live
              port: 11011
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 60
          readinessProbe:
            httpGet:
              path: /cm/internal/health/ready
              port: 11011
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 60
          envFrom:
          - configMapRef:
              name: config
